/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import db_conection_package.Mensaje_Usuario;
import java.awt.ComponentOrientation;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import returned_models.EnviarMensajesUsuario;
import user_session.SessionManager;


/**
 *
 * @author Nancy
 */
public class Chat extends javax.swing.JFrame {
    private String destinatario;
         
    /**
     * Creates new form Chat
     */
    
    public Chat()
    {
        
    }
    public Chat(String username) {
        this.destinatario = username;
        initComponents();
        
        Socket s;
        try {
            String direccionServidor = "10.147.17.147";
            InetAddress direccion = InetAddress.getByName(direccionServidor);
            s = new Socket(direccion, 1234);
            
            ObjectInputStream chat = new ObjectInputStream(s.getInputStream());
            try {
                ArrayList<Mensaje_Usuario> chatRecibido = (ArrayList<Mensaje_Usuario>)chat.readObject();
                String remitente = SessionManager.getUsername();
                
                for(Mensaje_Usuario msg: chatRecibido)
                {
                    if(msg.username_destinatario.equals(remitente))
                    {
                        CampoChat.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
                    }
                    else
                    {
                        CampoChat.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        EnviarMsgButton = new javax.swing.JButton();
        campoMsg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoChat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(226, 380));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        EnviarMsgButton.setText("Enviar");
        EnviarMsgButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarMsgButtonMouseClicked(evt);
            }
        });
        EnviarMsgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarMsgButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(EnviarMsgButton, gridBagConstraints);

        campoMsg.setColumns(15);
        campoMsg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        campoMsg.setMargin(new java.awt.Insets(2, 2, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(campoMsg, gridBagConstraints);

        CampoChat.setEditable(false);
        CampoChat.setColumns(15);
        CampoChat.setRows(15);
        jScrollPane1.setViewportView(CampoChat);

        getContentPane().add(jScrollPane1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarMsgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarMsgButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarMsgButtonActionPerformed

    private void EnviarMsgButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMsgButtonMouseClicked
        String mensaje = campoMsg.getText();
        CampoChat.setText(mensaje);
        String remitente = SessionManager.getUsername();
        
        EnviarMensajesUsuario msg = new EnviarMensajesUsuario(remitente, destinatario, mensaje);
        
        Socket s;
        try {
            String direccionServidor = "10.147.17.147";
            InetAddress direccion = InetAddress.getByName(direccionServidor);
            s = new Socket(direccion, 1234);
            
            DataOutputStream funcion = new DataOutputStream(s.getOutputStream());
            funcion.writeUTF("enviar_mensaje_usuario");
            
            ObjectOutputStream msgEnviar = new ObjectOutputStream(s.getOutputStream());
            msgEnviar.writeObject(msg);
            
        } catch (IOException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
        CampoChat.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }//GEN-LAST:event_EnviarMsgButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CampoChat;
    private javax.swing.JButton EnviarMsgButton;
    private javax.swing.JTextField campoMsg;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
